app.py
from flask import Flask, request, render_template, redirect, url_for
from routes.weather_routes import reading_bp

app = Flask(__name__)
app.config.from_object('config')

app.register_blueprint(reading_bp, url_prefix='/weather')

@app.route('/')
def index():
    '''Renders home page. '''
    return render_template('home.html')

controllers/weather.py
from flask import Flask, render_template, redirect, url_for, request
from helpers.weatherman import *
from helpers.calculations import *
from helpers.report import *
from controllers.weather import *


def index():
    return render_template('home.html')


def year():
    if request.method == "GET":
        return render_template('year.html')
    year = request.form.get("year")
    file_name = "weatherfiles/Murree_weather_" + year
    parse = ParsingData()
    weather_readings = parse.year_parsing(file_name)

    calculations = ReportCalculations()
    highest, lowest, humid = calculations.year_calculations(weather_readings)

    results = Results()
    results.year_results(highest, lowest, humid)
    
    return render_template("year_result.html", data=results)


def month():
    if request.method == 'GET':
        return render_template('month.html')
    year = request.form.get("year")
    month = request.form.get("month")
    file_name = ("weatherfiles/Murree_weather_" + year + "_" 
                                        + month + ".txt")

    parse = ParsingData()
    weather_readings = parse.month_parsing(file_name)

    highest_avg, lowest_avg, humid_avg = ReportCalculations.month_calculations(weather_readings)

    results = Results()
    results.month_results(highest_avg, lowest_avg, humid_avg)

    return render_template("month_result.html", data=results)


def chart():
    return render_template('charts.html')


def h_chart():
    year = request.form.get("year")
    month = request.form.get("month")
    file_name = ("weatherfiles/Murree_weather_" + year + "_"
                    + month + ".txt")

    parse = ParsingData()

    weather_readings = parse.month_parsing(file_name)

    return render_template("horizontal_chart.html", data=weather_readings)


def v_chart():
    year = request.form.get("year")
    month = request.form.get("month")
    file_name = ("weatherfiles/Murree_weather_" + year + "_"
                    + month + ".txt")

    parse = ParsingData()

    weather_readings = parse.month_parsing(file_name)

    return render_template("v_chart.html", data=weather_readings)

routes/weather_routes.py
from flask import Blueprint
from controllers.weather import login, signup, home, year
from controllers.weather import month, charts, horizontal_chart, vertical_chart

reading_blueprint = Blueprint('reading_blueprint', __name__)

reading_blueprint.route('/home/', methods=['GET'])(home)
reading_blueprint.route('/signup/', methods=['GET', 'POST'])(signup)
reading_blueprint.route('/login/', methods=['GET', 'POST'])(login)
reading_blueprint.route('/year/', methods=['GET', 'POST'])(year)
reading_blueprint.route('/month/', methods=['GET', 'POST'])(month)
reading_blueprint.route('/charts/', methods=['GET'])(charts)
reading_blueprint.route('/charts/horizontal-chart/',
                        methods=['GET', 'POST'])(horizontal_chart)
reading_blueprint.route('/charts/vertical-chart/',
                        methods=['GET', 'POST'])(vertical_chart)

templates/charts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
    <link href="/static/style.css" rel="stylesheet" >
    <title>WeatherMan App</title>
</head>
<body>
    <h1>Charts</h1>
    <div class="center">
        <form method="POST">
            <label name="year">Enter year: </label>
            <input placeholder="e.g 2006" name="year" for="year" value="{{year}}" >
    
            <label name="month">Enter month: </label>
            <select name="month" id="month" value="{{month}}">
                <option>--------</option>
                <option value="Jan">January</option>
                <option value="Feb">Feburary</option>
                <option value="Mar">March</option>
                <option value="Apr">April</option>
                <option value="May">May</option>
                <option value="Jun">June</option>
                <option value="Jul">July</option>
                <option value="Aug">August</option>
                <option value="Sep">September</option>
                <option value="Oct">October</option>
                <option value="Nov">November</option>
                <option value="Dec">December</option>
              </select>
    
            <button class="button-9" formaction="{{ url_for("reading_blueprint.horizontal_chart")}}" type="submit">Horizontal Chart</button>
            <button class="button-9" formaction="{{ url_for("reading_blueprint.vertical_chart")}}" type="submit">Vertical Chart</button>
        </form>
    </div>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
    <link href="/static/style.css" rel="stylesheet" >
    <title>WeatherMan App</title>
</head>
<body>
    <h1>WeatherMan App</h1>
    <div class="center">
        <button class="button-9" role="button" onclick="location.href = '/weather/year'">Year Report</button>
        <button class="button-9" onclick="location.href = '/weather/month'">Month Report</button>
        <button class="button-9" onclick="location.href = '/weather/chart'">Month Chart</button>
        <button class="button-9" onclick="location.href = '/weather/charts'">Month Chart</button>
        <button class="button-9" onclick="location.href = '/weather/charts'">Month Chart</button>
    </div>
</body>
</html>

templates/horizontal_chart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
    <link href="/static/style.css" rel="stylesheet" >
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <title>WeatherMan App</title>
</head>
<body>
    <h2> Horizontal Chart</h2>
        {% if data %}
            {% for day in data %}
            <div class="outer-div-horizontal">
                <div class="horizontal-chart-container">
                    <p class="day-label"> Day {{day['date']}}</p>
                    <canvas class="bar-chart" width="300" height="30" max_temp="{{ day['max_temp'] }}" min_temp="{{day['min_temp']}}" day="{{ day['date'] }}"></canvas>
                    <p class="max_temp" > {{day['max_temp']}}&deg;C<p>
                    <p class="dash">-</p>
                    <p class="min_temp">{{day['min_temp']}}&deg;C</p>
                </div>
                <br>
            </div>
            {% endfor %}
            <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
            <script src="{{ url_for('static', filename='horizontal_chart.js')}}"></script>
        {% endif %}
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
    <link href="/static/style.css" rel="stylesheet" >
    <title>WeatherMan App</title>
</head>
<body>
    <h1>Login</h1>
    <div class="center">
        <form method="post">
            <input type="text" name="username" value="{{username}}" placeholder="Enter username" action="{{ url_for("reading_blueprint.login")}}" required>
            <input type="password" name="password" value="{{password}}" placeholder="Enter password" required>
            <button class="button-9" type="submit">Submit</button>
            <a class="signup_link" href='/weather/signup'>New to Weatherman? Sign Up.</a>
        </form>

    </div>   
</body>
</html>

templates/month.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
    <link href="/static/style.css" rel="stylesheet" >
    <title>WeatherMan App</title>
</head>
<body>
    <h1>Month Report</h1>
    <div class="center">
        <form method="POST" action="{{ url_for("reading_blueprint.month")}}">
            <label name="year">Enter year: </label>
            <input type="number" min="2004" max="2016" placeholder="e.g 2006" name="year" for="year" value="{{year}}">
            <label name="month">Enter month: </label>
            <select name="month" id="month" value="{{month}}">
                <option>--------</option>
                <option value="Jan">January</option>
                <option value="Feb">Feburary</option>
                <option value="Mar">March</option>
                <option value="Apr">April</option>
                <option value="May">May</option>
                <option value="Jun">June</option>
                <option value="Jul">July</option>
                <option value="Aug">August</option>
                <option value="Sep">September</option>
                <option value="Oct">October</option>
                <option value="Nov">November</option>
                <option value="Dec">December</option>
              </select>
            <button class="button-9" type="submit">Submit</button>
        </form>
    </div>
</body>
</html>

templates/month_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
    <link href="/static/style.css" rel="stylesheet" >
    <title>WeatherMan App</title>
</head>
<body>
    <div class="widget-div">
        <div class="widget">
            
            <div class="left-panel panel">
                <div class="date">
                </div>
                <div class="city">
                    Highest Average
                </div>
                <div class="temp">
                   {{data.highest_avg}}&deg;
                </div>
            </div>
            <div class="right-panel panel">
            </div>
        </div>
       
        <div class="widget">
                
            <div class="left-panel panel">
                <div class="date">
                </div>
                <div class="city">
                    Lowest Average
                </div>
                <div class="temp">
                    {{data.lowest_avg}}&deg;
                </div>
            </div>
            <div class="right-panel panel">
            </div>
        </div>
        
        <div class="widget">
                
            <div class="left-panel panel">
                <div class="date">
                </div>
                <div class="city">
                    Average Humidity
                </div>
                <div class="temp">
                    {{data.humid_avg}}%
                </div>
            </div>
            <div class="right-panel panel">
            </div>
        </div>
    </div>
</body>
</html>

templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
    <link href="/static/style.css" rel="stylesheet" >
    <title>WeatherMan App</title>
</head>
<body>
    <h1>Sign Up</h1>
    <div class="center">
        <form method="post" action="{{ url_for("reading_blueprint.signup")}}"> 
            <input type="text" name="username" value="{{username}}" placeholder="Enter username" required>
            <input type="password" name="password" value="{{password}}" placeholder="Enter password" required>
            <button onclick="location.href = '/weather/login/'" class="button-9" type="submit">Submit</button>
        </form>
    </div>   
</body>
</html>

templates/v_chart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
    <link href="/static/style.css" rel="stylesheet" >
    <title>WeatherMan App</title>
</head>
<body>
    <h2 style="color: white; text-align: center; margin: 50px"> Vertical Chart</h2>
    <div>
        {% if data %}
        {% set size = data|length %}
        {% for i in range(size) %}
            {% set date = (data[i].day).split('-') %}
            {% set day = date[2] %}
            {% set max_temp = data[i].max_temp %}
            <div class="bg" style="display: flex; align-items: center;">
                {% if max_temp != '' %}
                    <p>Day: {{day}} </p>
                    {% for j in range(max_temp) %}
                        <li style="color: red; display: inline;">+</li>
                    {% endfor %}
                    <p>{{max_temp}}&deg;C</p>
                {% endif %}
            </div>
            <div class="bg" style="display: flex; align-items: center;">  
                {% set min_temp = data[i].min_temp %}
                {% if min_temp != '' %}
                    <p>Day: {{day}} </p>
                    {% for j in range(min_temp) %}
                        <li style="color: blue; display: inline;">+</li>
                    {% endfor %}
                    <p> {{min_temp}}&deg;C</p>
                {% endif %}
            </div>
            <br>
        {% endfor %}
    {% endif %}
    </div>
    
</body>
</html>

templates/vertical_chart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
    <link href="/static/style.css" rel="stylesheet" >
    <title>WeatherMan App</title>
</head>
<body>
    <h2> Vertical Chart</h2>
    {% if data %}
            {% for day in data %}
                <div class="outer-div">
                    <div class="chart-container">
                        <p class="day-text"> Day {{day['date']}}</p>
                        <canvas class="red-bar-chart" width="500" height="30" max_temp="{{ day['max_temp'] }}"></canvas>
                        <br>
                        <canvas class="blue-bar-chart" width="500" height="30" min_temp="{{ day['min_temp'] }}"></canvas>
                    </div>
                    <br>
                </div>
            {% endfor %}
            <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
            <script src="{{ url_for('static', filename='vertical_chart.js')}}"></script>
        {% endif %}
</body>
</html>

templates/year.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
    <link href="/static/style.css" rel="stylesheet" >
    <title>WeatherMan App</title>
</head>
<body>
    <h1>Enter Year</h1>
    <div class="center">
        <form method="POST" action="{{ url_for("reading_blueprint.year")}}">
            <input type="number" min="2004" max="2016" id="year" value="{{year}}" placeholder="e.g 2006" name="year" for="year">
            <button class="button-9" type="submit">Submit</button>
        </form>
    </div>
</body>
</html>

templates/year_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
    <link href="/static/style.css" rel="stylesheet" >
    <title>WeatherMan App</title>
</head>
<body>
    <div class="widget-div">
        <div class="widget">
            
            <div class="left-panel panel">
                <div class="date">
                    {{data.highest_day}}, {{data.highest_month}}
                </div>
                <div class="city">
                    Highest Temperature
                </div>
                <div class="temp">
                   {{data.highest}}&deg;
                </div>
            </div>
            <div class="right-panel panel">
            </div>
        </div>
       
        <div class="widget">
                
            <div class="left-panel panel">
                <div class="date">
                    {{data.lowest_day}}, {{data.lowest_month}}
                </div>
                <div class="city">
                    Lowest Temperature
                </div>
                <div class="temp">
                    {{data.lowest}}&deg;
                </div>
            </div>
            <div class="right-panel panel">
            </div>
        </div>
        
        <div class="widget">
                
            <div class="left-panel panel">
                <div class="date">
                    {{data.humid_day}}, {{data.humid_month}}
                </div>
                <div class="city">
                    Most Humid Day
                </div>
                <div class="temp">
                    {{data.humidity}}%
                </div>
            </div>
            <div class="right-panel panel">
            </div>
        </div>
    </div>    
</body>
</html>